apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-u3sb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-u3sb@sha256:881dc8c61289b341d9a22cf8705a16ee4a808e3a9c40e04baf55dda1720ac697
        name: my-nodejs
        resources: {}
status: {}
